### ISSUE TITLE
AttributeError: 'mappingproxy' object has no attribute 'update'

### ISSUE THREAD

**Issue by kong-fan-xing123** [kong-fan-xing123/pyaccessctrl#1]
AttributeError: 'mappingproxy' object has no attribute 'update'

**Comment by kong-fan-xing123** [comment]
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "/home/kfx/pyaccesscontrol.py", line 20, in deco`
`    class onInstance:`
`  File "/home/kfx/Python-3.10.0b3/Lib/functools.py", line 58, in update_wrapper`
`    getattr(wrapper, attr).update(getattr(wrapped, attr, {}))`
`AttributeError: 'mappingproxy' object has no attribute 'update'`

**Comment by kong-fan-xing123** [comment]
.     .       .
   .      .     .
